### ISSUE TITLE
[macos] 'Stat' marked 'override' but does not override any member functions

### ISSUE THREAD

**Issue by xhaggi** [notspiff/vfs.rar#19]
The following error occurs while compiling on MacOS.
Removing `override` will fix the issue, but not sure why it happens because the method signature looks fine and all other methods use override too. Maybe something to do with the second parameter `struct __stat64* buffer`.

```
vfs.rar/src/RarFile.cpp:397:15: error: 'Stat' marked 'override' but does not override any member functions
  virtual int Stat(const VFSURL& url, struct __stat64* buffer) override;
```

**Comment by notspiff** [comment]
The infamous stat64 strikes again. No idea how it is typedef'd these days i fought and fixed it years ago. it is a different type kodi side now.compared to kodiplatform, or thereabout. Removing override doesnt fix things, override saved us and pointed out the error.

**Comment by xhaggi** [comment]
>Removing override doesnt fix things, override saved us and pointed out the error.

Let me correct my statement, it complies without.

It's strange that it only appears on macos. On linux (ubuntu) it works without the compiler error. Got some warnings about P8 redefine stat64, but temporary remove that define doesn't fix the override error. Could take another look at it this week.

**Comment by notspiff** [comment]
I understood what you meant, point is you are no longer overriding the base class method, but rather overloading it with a new stat because stat64 means one thing in binding header and something else i  addon source.

**Comment by notspiff** [comment]
in add-on binding (through Filesystem.h)

```
#if !defined(_WIN32)
  #include <sys/stat.h>
  #if !defined(__stat64)
    #define __stat64 stat64
  #endif
#endif
```
while in platform
```
#define __stat64 stat
#define stat64 stat
```

due to the nasty define usage we end up with the actual stat64 in add-on binding, while the platform stuff makes stat64 into stat. flipping the include orders should take care of it in a nasty way (but hey, this is already rather nasty).

**Comment by xhaggi** [comment]
Don't get me wrong I don't want to remove override, that's why I add this issue. I thought you know the reason or point me to the right place ;)

**Comment by xhaggi** [comment]
Thanks for pointing me to right direction. Will adjust the include order.

**Comment by notspiff** [comment]
np, we were on the same page all along, except i wanted to explain why removing override made it build (and ended up adding confusion in the process) while i was waiting for my laptop which busy with .. entertaining windows.
