### ISSUE TITLE
Addon seems to compete with vfs.libarchive

### ISSUE THREAD

**Issue by Tratoschek** [notspiff/vfs.rar#29]
Activating this addon and [vfs.libarchive](/notspiff/vfs.libarchive) results in ignoring any rar-archive (maybe because both addons register the rar extension).

**Comment by notspiff** [comment]
yes, that is to be expected. use one or the other.

**Comment by Tratoschek** [comment]
Ok. Can you mention it in the README? My expectation was that Kodi either warn about multiple registrations of the same handler or somehow prefer one of them. Of course this is a Kodi issue but some users may be less confused, if you mention it in the README.

**Comment by AlwinEsch** [comment]
This need changes on Kodi itself, I look in future about a fix it and allow a selection in settings about wanted addon to use

**Comment by zach-morris** [comment]
Would it be possible to add a unique protocol for vfs.rar?  Especially with Kodi v19 and solid rar archive support if you were to add:
```
protocols="rar|rar_solid"
```
or
```
protocols="rar|rars"
```
or similar.  Then on the python side the addon creator could define it as a unique option.

**Comment by AlwinEsch** [comment]
I think to add a system to make the extensions and mimetypes selectable and set the wanted addon (or to Kodi if supported) in Settings and also inform the user if he install a addon where already supported somewhere else.

There also some other addons where it supported on different.

Can also look then to allow python side to force to one.

**Comment by AlwinEsch** [comment]
It think to remove the RAR support from vfs.libarchive when this here is stable enough.

For future, maybe Kodi N* I look to allow selection like wrote in comment before.

**Comment by zach-morris** [comment]
I was able to resolve this issue via python as a workaround, using [this module](https://github.com/zach-morris/script.module.archive_tool) for testing.

```
#Sleep call is currently requried to avoid crashing Kodi
xbmc.sleep(1000)
xbmc.executeJSONRPC('{ "jsonrpc": "2.0", "method": "Addons.SetAddonEnabled","params":{"addonid": "vfs.libarchive", "enabled": false} }') #Temporarily disable vfs.libarchive
xbmc.sleep(1000)
my_archive = archive_tool.archive_tool(archive_file = 'myfile.rar',directory_out = '/my/output_directory/', use_vfs_rar=True) #Current archive object using vfs.rar instead of vfs.libarchive

xbmc.executeJSONRPC('{ "jsonrpc": "2.0", "method": "Addons.SetAddonEnabled","params":{"addonid": "vfs.libarchive", "enabled": true} }') #re-enable vfs.libarchive
xbmc.sleep(1000)
```

**Comment by highlandr** [comment]
I would just remove the rar from libarchive :)
If you need tests and logs to get RAR more stable just ask!
The only thing I see different from the old 17.6 kodi is that browsing now is a bit more slower (when browsing directories with big library of rar files).
Cheers!

**Comment by AlwinEsch** [comment]
I remove next days the rar support from vfs.libarchive addon, think here now more stable as the other.

About the speed, before was a more own hack way used to use the RAR lib (also was his lib code there much smaller), with change to newest version of them (v5) was it no more so easy to use hack way and was changed to take original API about.

Maybe I can become it a bit faster, but for the old speed I think it doesn't work anymore

**Comment by AlwinEsch** [comment]
On Kodi Matrix by vfs.libarchive is now the rar support removed and this here then always usable.

**Comment by zach-morris** [comment]
Does [this](https://github.com/xbmc/xbmc/pull/18422#event-3769141747) recent merge change the methodology here at all?

**Comment by AlwinEsch** [comment]
There only about audiodecoder where checked before vfs addons (and if audiodecoders failed to use VFS).
About VFS only currently not possible. 

The vfs.sacd was more of a special case because its ISO something else. Regarding RAR this would be more difficult, since vfs.libarchive and vfs.rar support exactly the same format.
